//! SDK documentation output policy and built-in markdown renderers.
//!
//! Documentation output is part of gnr8's owned SDK surface.

use std::fmt::Write as _;

use crate::graph::{ApiGraph, MediaExample, OperationDocsPolicy, Type};
use crate::sdk::model::SdkModel;
use crate::sdk::Artifacts;

pub use gnr8::sdk::docs::SdkDocs;

/// Write SDK documentation artifacts under `dir`.
///
pub(crate) fn write_sdk_docs(
    out: &mut Artifacts,
    dir: &str,
    language: &str,
    package: &str,
    ir: &ApiGraph,
    _model: &SdkModel,
    docs: &SdkDocs,
) -> Result<(), crate::CoreError> {
    if docs.is_none() {
        return Ok(());
    }
    let dir = dir.trim_end_matches('/');
    if !docs.is_none() {
        out.create(
            format!("{dir}/README.md"),
            sdk_readme(language, package, ir),
        )?;
        out.create(
            format!("{dir}/reference.md"),
            sdk_reference(language, package, ir),
        )?;
    }
    Ok(())
}

fn sdk_readme(language: &str, package: &str, ir: &ApiGraph) -> String {
    let mut text = format!(
        "# {title} {language} SDK\n\n\
         This directory is generated by `gnr8`. Do not edit generated files directly; edit \
         `.gnr8/src/main.rs` or the source service, then run `gnr8 generate`.\n\n\
         ## Package\n\n\
         - Language: {language}\n\
         - Package/module: `{package}`\n\
         - Base path: `{base_path}`\n\
         - Operations: {operation_count}\n\
         - Schemas: {schema_count}\n\n",
        title = ir.title,
        base_path = ir.base_path,
        operation_count = ir.operations.len(),
        schema_count = ir.schemas.len()
    );
    text.push_str("## Agent workflow\n\n");
    text.push_str("1. Read `reference.md` in this directory for operation and schema names.\n");
    // The error type is named per language; a combined "APIError/ApiError" would send half of
    // readers looking for a symbol their SDK does not export.
    let error_type = match language {
        "Go" => "`*APIError`",
        _ => "`ApiError`",
    };
    let construct = match language {
        "TypeScript" => "2. Construct the generated `Client` with `{ baseUrl }`.\n",
        _ => "2. Construct the generated `Client` with the service base URL.\n",
    };
    text.push_str(construct);
    text.push_str(
        "3. Pass typed request models and path/query parameters according to the generated method signatures.\n",
    );
    let _ = writeln!(
        text,
        "4. Handle generated {error_type} values for rejected HTTP responses.\n"
    );
    // The timeout knob does not bound the same span in every language, and a caller who assumes
    // it does will size it wrong. Say so where they will read it.
    let timeout_note = match language {
        "Go" => concat!(
            "## Retries and timeouts\n\n",
            "`WithTimeout` bounds the whole call, including retries and the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Cancelling the context interrupts a retry wait.\n\n"
        ),
        "Python" => concat!(
            "## Retries and timeouts\n\n",
            "`timeout` bounds each individual attempt, not the whole call: with retries, total ",
            "wall time can reach `timeout x (max_retries + 1)` plus the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Retry waits are not interruptible.\n\n"
        ),
        "TypeScript" => concat!(
            "## Retries and timeouts\n\n",
            "`timeoutMs` bounds each individual attempt, not the whole call: with retries, total ",
            "wall time can reach `timeoutMs x (maxRetries + 1)` plus the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Pass `signal` to interrupt a retry wait.\n\n"
        ),
        _ => "",
    };
    text.push_str(timeout_note);
    match language {
        "Go" => text.push_str(
            "## Go quick start\n\n\
             ```go\n\
             client := sdk.NewClient(\"https://api.example.com\")\n\
             // Call methods on client with context.Context first.\n\
             ```\n",
        ),
        "Python" => text.push_str(
            "## Python quick start\n\n\
             ```python\n\
             from sdk import Client\n\
             client = Client(\"https://api.example.com\")\n\
             # Call generated methods with typed models from this package.\n\
             ```\n",
        ),
        // The TypeScript constructor takes a ClientOptions object, not a bare URL string.
        "TypeScript" => text.push_str(
            "## TypeScript quick start\n\n\
             ```typescript\n\
             import { Client } from './client';\n\
             const client = new Client({ baseUrl: 'https://api.example.com' });\n\
             // Call generated async methods with typed request objects.\n\
             ```\n",
        ),
        _ => {}
    }
    text
}

fn sdk_reference(language: &str, package: &str, ir: &ApiGraph) -> String {
    let mut text = format!(
        "# SDK Reference\n\n\
         Generated by `gnr8` for `{package}` ({language}).\n\n\
         ## Operations\n\n\
         | Method | Path | Operation | Request | Responses |\n\
         |--|--|--|--|--|\n"
    );
    for op in &ir.operations {
        let request = op
            .request_body
            .as_ref()
            .map_or("-", |request| request.ref_id.as_str());
        let responses = op
            .responses
            .iter()
            .map(|response| response.status.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            text,
            "| {} | `{}` | `{}` | `{}` | {} |",
            op.method, op.path, op.id, request, responses
        );
    }
    append_reference_operation_docs(&mut text, ir);
    text.push_str("\n## Schemas\n\n| Schema | Kind |\n|--|--|\n");
    for schema in &ir.schemas {
        let _ = writeln!(
            text,
            "| `{}` | {} |",
            schema.name,
            schema_kind(&schema.body)
        );
    }
    append_reference_diagnostics(&mut text, ir);
    text
}

/// The stable code for "a package loader stage failed", which the reference never publishes.
///
/// Matching the CODE is what this identity is for — it is the same key `DiagnosticPolicy` matches
/// on — so this is a policy decision about a class of diagnostic, not a reading of its text.
const SOURCE_LOAD_FAILED: &str = "source.load.failed";

/// Whether a diagnostic belongs in a published SDK reference.
///
/// Two clauses, for two different reasons. Both exist because a generated document is COMMITTED:
/// it is read by people who did not run the pipeline, and it is compared byte-for-byte by
/// `gnr8 check`.
///
/// 1. **The location must name a file inside the analyzed module.** A location outside it — a
///    dependency, the standard library, a downloaded toolchain under the module cache — is not a
///    fact about the API this document describes, and it is machine-dependent: it holds the
///    reader's home directory and module-cache layout. Publishing one makes two developers with
///    byte-identical source commit different bytes, which surfaces as `gnr8 check` drift that no
///    source change explains (issue #67).
///
/// 2. **It must describe the API, not whether the source could be read at all.** A load failure
///    means there was no surface to describe, so it is not a gap in the published contract — and
///    its message is the package loader's own text, which can quote a filesystem path wherever the
///    loader chose to. Excluding the class removes that whole exposure without gnr8 ever reading a
///    diagnostic's message to decide.
///
/// Nothing is lost. Every diagnostic still travels with the graph and still reaches
/// `gnr8 inspect graph`, `gnr8 doctor` (which exits non-zero on error severity), and `-v` output —
/// reports, rather than committed artifacts.
fn is_publishable(diagnostic: &crate::graph::Diagnostic) -> bool {
    crate::graph::is_module_relative(&diagnostic.file) && diagnostic.code != SOURCE_LOAD_FAILED
}

/// Render the "Diagnostics" section: what extraction could not state about THIS API.
///
/// The section is omitted entirely when nothing is publishable, rather than emitting an empty
/// heading (see [`is_publishable`]).
fn append_reference_diagnostics(text: &mut String, ir: &ApiGraph) {
    let published: Vec<&crate::graph::Diagnostic> = ir
        .diagnostics
        .iter()
        .filter(|d| is_publishable(d))
        .collect();
    if published.is_empty() {
        return;
    }
    text.push_str("\n## Diagnostics\n\n");
    for diagnostic in published {
        let _ = writeln!(
            text,
            "- {}: {} ({}:{})",
            diagnostic.severity, diagnostic.message, diagnostic.file, diagnostic.line
        );
    }
}

/// Render the "Operation Documentation" section.
///
/// Iteration is over OPERATIONS, not over `operation_docs`: prose lives on the operation
/// (AGENTS.md rule 3), and effective tags can come from the operation's group without a policy
/// entry. The policy is joined in for the facts that genuinely are policy — deprecation and
/// examples.
fn append_reference_operation_docs(text: &mut String, ir: &ApiGraph) {
    let effective_tags = crate::graph::EffectiveOperationTags::new(ir);
    let documented: Vec<(&crate::graph::Operation, Option<&OperationDocsPolicy>)> = ir
        .operations
        .iter()
        .map(|op| {
            let policy = ir
                .operation_docs
                .iter()
                .find(|policy| policy.operation_id == op.id);
            (op, policy)
        })
        .filter(|(op, policy)| {
            op.summary.is_some()
                || op.description.is_some()
                || policy.is_some()
                || !effective_tags.resolve(op).is_empty()
        })
        .collect();
    if documented.is_empty() {
        return;
    }
    text.push_str("\n## Operation Documentation\n\n");
    for (op, policy) in documented {
        let _ = writeln!(text, "### `{}`\n", op.id);
        append_operation_docs_body(text, &effective_tags, op, policy);
    }
}

fn append_operation_docs_body(
    text: &mut String,
    effective_tags: &crate::graph::EffectiveOperationTags<'_>,
    op: &crate::graph::Operation,
    policy: Option<&OperationDocsPolicy>,
) {
    if let Some(summary) = op.summary.as_deref() {
        let _ = writeln!(text, "- Summary: {summary}");
    }
    if policy.is_some_and(|policy| policy.deprecated) {
        text.push_str("- Deprecated: yes\n");
    }
    let tags = effective_tags.resolve(op);
    if !tags.is_empty() {
        let joined = tags
            .iter()
            .map(|tag| format!("`{tag}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(text, "- Tags: {joined}");
    }
    if let Some(description) = op.description.as_deref() {
        let _ = writeln!(text, "\n{description}\n");
    } else {
        text.push('\n');
    }
    if let Some(policy) = policy {
        append_examples(text, "Request examples", &policy.request_examples);
        for response in &policy.responses {
            if response.description.is_none() && response.examples.is_empty() {
                continue;
            }
            let _ = writeln!(text, "- Response `{}`:", response.status);
            if let Some(description) = &response.description {
                let _ = writeln!(text, "  - Description: {description}");
            }
            append_examples_with_indent(text, "Examples", &response.examples, "  ");
        }
        if !policy.request_examples.is_empty()
            || policy
                .responses
                .iter()
                .any(|response| response.description.is_some() || !response.examples.is_empty())
        {
            text.push('\n');
        }
    }
}

fn append_examples(text: &mut String, label: &str, examples: &[MediaExample]) {
    append_examples_with_indent(text, label, examples, "");
}

fn append_examples_with_indent(
    text: &mut String,
    label: &str,
    examples: &[MediaExample],
    indent: &str,
) {
    if examples.is_empty() {
        return;
    }
    let _ = writeln!(text, "{indent}- {label}:");
    for example in examples {
        let value = serde_json::to_string(&example.value).unwrap_or_else(|_| "null".to_string());
        let _ = writeln!(
            text,
            "{indent}  - `{}` (`{}`): `{}`",
            example.name, example.content_type, value
        );
    }
}

fn schema_kind(schema: &Type) -> &'static str {
    match schema {
        Type::Object(_) => "object",
        Type::Enum(_) => "enum",
        Type::Primitive(_) => "primitive",
        Type::WellKnown(_) => "well-known",
        Type::Array(_) => "array",
        Type::Map { .. } => "map",
        Type::Named(_) => "reference",
        Type::Union(_) => "union",
        Type::Any {} => "any",
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::{sdk_reference, SdkDocs};
    use crate::graph::{
        ApiGraph, Diagnostic, DiagnosticCategory, Operation, OperationDocsPolicy, SourceSpan,
    };

    #[test]
    fn bool_conversion_maps_true_to_reference_and_false_to_none() {
        assert!(!SdkDocs::from(true).is_none());
        assert!(SdkDocs::from(false).is_none());
    }

    fn diagnostic(code: &str, severity: &str, message: &str, file: &str) -> Diagnostic {
        Diagnostic::new(
            code,
            DiagnosticCategory::Source,
            severity,
            message,
            SourceSpan {
                file: file.to_string(),
                start_line: 1,
                end_line: 1,
            },
        )
    }

    /// A diagnostic about the API surface, which is what the section is for.
    fn contract_diagnostic(severity: &str, message: &str, file: &str) -> Diagnostic {
        diagnostic("request.parameter.unresolved", severity, message, file)
    }

    /// A diagnostic about a package that did not load, which is not.
    fn load_failure(message: &str, file: &str) -> Diagnostic {
        diagnostic("source.load.failed", "ERROR", message, file)
    }

    fn graph_with(diagnostics: Vec<Diagnostic>) -> ApiGraph {
        ApiGraph {
            diagnostics,
            ..ApiGraph::default()
        }
    }

    fn operation(id: &str, group: Option<&str>) -> Operation {
        Operation {
            id: id.to_string(),
            method: "GET".to_string(),
            path: format!("/{id}"),
            handler: id.to_string(),
            summary: Some(format!("Document {id}.")),
            description: None,
            group: group.map(str::to_string),
            middleware: Vec::new(),
            params: Vec::new(),
            request_body: None,
            request_body_required: true,
            request_body_content_type: None,
            request_body_variants: Vec::new(),
            responses: Vec::new(),
            security: Vec::new(),
            security_overrides_global: false,
            provenance: SourceSpan {
                file: "books.rs".to_string(),
                start_line: 1,
                end_line: 1,
            },
        }
    }

    #[test]
    fn reference_uses_canonical_tags_for_policy_group_and_empty_results() {
        let mut grouped = operation("grouped", Some("Books"));
        grouped.summary = None;
        let graph = ApiGraph {
            operations: vec![
                grouped,
                operation("classified", Some("Reports")),
                operation("untagged", None),
            ],
            operation_docs: vec![OperationDocsPolicy {
                operation_id: "classified".to_string(),
                openapi_operation_id: None,
                deprecated: false,
                tags: vec!["internal".to_string(), "partner".to_string()],
                request_examples: Vec::new(),
                request_content_types: Vec::new(),
                responses: Vec::new(),
            }],
            ..ApiGraph::default()
        };

        let reference = sdk_reference("Go", "example.com/sdk", &graph);
        assert!(reference.contains("- Tags: `Books`"), "{reference}");
        assert!(
            reference.contains("- Tags: `internal`, `partner`"),
            "{reference}"
        );
        assert!(!reference.contains("- Tags: `Reports`"), "{reference}");
        assert!(reference.contains("### `untagged`"), "{reference}");
        let untagged = reference.split("### `untagged`").nth(1).unwrap_or_default();
        assert!(!untagged.contains("- Tags:"), "{untagged}");
    }

    /// A diagnostic about the analyzed module is exactly what this section is for: it tells an
    /// agent reading the SDK what the API contract does not state.
    #[test]
    fn a_diagnostic_inside_the_module_is_published() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "untyped query param 'genre' on GET /books",
                "internal/http/handlers.go",
            )]),
        );
        assert!(reference.contains("## Diagnostics"), "{reference}");
        assert!(
            reference.contains(
                "- WARN: untyped query param 'genre' on GET /books (internal/http/handlers.go:1)"
            ),
            "{reference}"
        );
    }

    /// Clause 1, isolated: a location outside the module carries the reader's home directory, so
    /// two developers with byte-identical source would commit different documents and `gnr8 check`
    /// would report drift that no source change explains (issue #67). The diagnostic is an ordinary
    /// contract diagnostic, so ONLY its location can be what excludes it.
    #[test]
    fn a_diagnostic_outside_the_module_is_not_published() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "untyped query param 'genre' on GET /books",
                "/Users/someone/go/pkg/mod/example.com/dep@v1.2.3/handlers.go",
            )]),
        );
        assert!(
            !reference.contains("## Diagnostics"),
            "a section with nothing publishable must not be emitted: {reference}"
        );
        assert!(!reference.contains("/Users/someone"), "{reference}");
    }

    /// Clause 2, isolated: a package that did not load leaves no API surface to describe, and its
    /// message is the package loader's own text, which can quote a filesystem path wherever the
    /// loader chose to. The location here is inside the module, so ONLY the class can exclude it.
    #[test]
    fn a_load_failure_is_not_published_even_from_inside_the_module() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![load_failure(
                "go/packages list error: no required module provides package x; \
                 open /Users/someone/go/pkg/mod/x: no such file",
                "internal/http/handlers.go",
            )]),
        );
        assert!(
            !reference.contains("## Diagnostics"),
            "a section with nothing publishable must not be emitted: {reference}"
        );
        assert!(!reference.contains("/Users/someone"), "{reference}");
        assert!(!reference.contains("go/packages list error"), "{reference}");
    }

    /// One unpublishable diagnostic must not take the publishable ones with it.
    #[test]
    fn publishable_diagnostics_survive_alongside_an_unpublishable_one() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![
                load_failure(
                    "go/packages type error: boom",
                    "/home/runner/go/pkg/mod/dep/dep.go",
                ),
                contract_diagnostic("WARN", "dynamic response in handler listBooks", "main.go"),
            ]),
        );
        assert!(reference.contains("## Diagnostics"), "{reference}");
        assert!(
            reference.contains("- WARN: dynamic response in handler listBooks (main.go:1)"),
            "{reference}"
        );
        assert!(!reference.contains("/home/runner"), "{reference}");
    }

    /// The rendered document must not depend on the machine that rendered it. Rendering the same
    /// graph on a host with a POSIX module cache and on one with a Windows module cache has to
    /// produce the same bytes, or the determinism guarantee holds only within one operating system.
    #[test]
    fn rendering_is_identical_whichever_absolute_path_shape_the_host_uses() {
        let posix = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "boom",
                "/home/runner/go/pkg/mod/dep/dep.go",
            )]),
        );
        let windows = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "boom",
                r"C:\Users\runner\go\pkg\mod\dep\dep.go",
            )]),
        );
        assert_eq!(posix, windows);
    }
}
