//! SDK documentation output policy: the `README.md` and `reference.md` an SDK target writes.
//!
//! Both are rendered from the docs model (`crate::docs`), built for this one SDK — the same builder
//! and the same renderer `StaticDocs` uses, viewed as a single file. The README's package lines name
//! the one consumer identity, and its quick start is the first sampled operation's call, byte for
//! byte as `reference.md` (and a `StaticDocs` page) prints it.

use std::fmt::Write as _;

use crate::docs::build::language_name;
use crate::docs::identity::{error_type, NO_IDENTITY_NOTE};
use crate::docs::markdown::escape::code_span;
use crate::docs::markdown::render;
use crate::docs::model::{DocsModel, ExampleDoc, SdkSamples, View};
use crate::graph::ApiGraph;
use crate::sdk::builtins::SiblingSdk;
use crate::sdk::Artifacts;
use crate::verify::ContractTestLanguage;
use crate::CoreError;

pub use gnr8::sdk::docs::SdkDocs;

/// Write the SDK's `README.md` and `reference.md` under its directory, from `ir` — the projected
/// graph the SDK itself is emitted from.
///
/// # Errors
///
/// Returns what the docs model's builder or renderer returns: an invalid declared example, prose
/// that breaks `reference.md`'s structure, or a sample that cannot be printed.
pub(crate) fn write_sdk_docs(
    out: &mut Artifacts,
    sdk: SiblingSdk<'_>,
    ir: &ApiGraph,
    docs: &SdkDocs,
) -> Result<(), CoreError> {
    if docs.is_none() {
        return Ok(());
    }
    let dir = sdk.dir().trim_end_matches('/');
    let model = DocsModel::build(ir, &[sdk], View::Sdk)?;
    out.create(format!("{dir}/README.md"), sdk_readme(&model, sdk))?;
    out.create(
        format!("{dir}/reference.md"),
        render::sdk_reference(&model, &format!("{dir}/reference.md"))?,
    )?;
    Ok(())
}

/// The first sampled operation's call for the model's one SDK: its id, request line and sample
/// block — the quick start, which `reference.md` prints byte for byte under that operation.
pub(crate) fn quick_start(model: &DocsModel) -> Option<(&str, &str, String)> {
    model.operations.iter().find_map(|op| match &op.example {
        ExampleDoc::Sampled { per_sdk, .. } => match per_sdk.first() {
            Some(SdkSamples::Code(samples)) => Some((
                op.id.as_str(),
                op.request_line.as_str(),
                render::sample_block(&samples.call),
            )),
            _ => None,
        },
        ExampleDoc::Refused(_) => None,
    })
}

fn sdk_readme(model: &DocsModel, sdk: SiblingSdk<'_>) -> String {
    let language = sdk.language();
    let name = language_name(language);
    let identity = model.sdks.first().and_then(|doc| doc.identity.as_ref());
    let mut text = format!(
        "# {title} {name} SDK\n\n\
         This directory is generated by `gnr8`. Do not edit generated files directly; edit \
         `.gnr8/src/main.rs` or the source service, then run `gnr8 generate`.\n\n\
         ## Package\n\n\
         - Language: {name}\n",
        title = model.api.title.trim(),
    );
    if let Some(identity) = identity {
        let _ = writeln!(text, "- Import: {}", code_span(identity.import()));
        let _ = writeln!(
            text,
            "- Install: {}",
            code_span(&identity.install_command())
        );
    }
    let _ = write!(
        text,
        "- Base path: `{base_path}`\n- Operations: {operations}\n- Schemas: {schemas}\n\n",
        base_path = model.api.base_path.as_deref().unwrap_or("/"),
        operations = model.operations.len(),
        schemas = model.schemas.len(),
    );
    if identity.is_none() {
        let _ = writeln!(text, "{NO_IDENTITY_NOTE}\n");
    }
    text.push_str("## Agent workflow\n\n");
    text.push_str(
        "1. Read `reference.md` in this directory for every operation, schema, error and \
         credential, each operation with its sample.\n",
    );
    let construct = match language {
        ContractTestLanguage::TypeScript => {
            "2. Construct the generated `Client` with `{ baseUrl }`.\n"
        }
        ContractTestLanguage::Go | ContractTestLanguage::Python => {
            "2. Construct the generated `Client` with the service base URL.\n"
        }
    };
    text.push_str(construct);
    text.push_str(
        "3. Pass typed request models and path/query parameters according to the generated method signatures.\n",
    );
    // The error type is named as this language's emitter spells it.
    let _ = writeln!(
        text,
        "4. Handle generated {} values for rejected HTTP responses.\n",
        code_span(&error_type(language))
    );
    // The timeout knob does not bound the same span in every language, and a caller who assumes
    // it does will size it wrong. Say so where they will read it.
    text.push_str(match language {
        ContractTestLanguage::Go => concat!(
            "## Retries and timeouts\n\n",
            "`WithTimeout` bounds the whole call, including retries and the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Cancelling the context interrupts a retry wait.\n\n"
        ),
        ContractTestLanguage::Python => concat!(
            "## Retries and timeouts\n\n",
            "`timeout` bounds each individual attempt, not the whole call: with retries, total ",
            "wall time can reach `timeout x (max_retries + 1)` plus the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Retry waits are not interruptible.\n\n"
        ),
        ContractTestLanguage::TypeScript => concat!(
            "## Retries and timeouts\n\n",
            "`timeoutMs` bounds each individual attempt, not the whole call: with retries, total ",
            "wall time can reach `timeoutMs x (maxRetries + 1)` plus the waits between them. ",
            "Total time spent waiting between retries is capped at 60s, so a longer `Retry-After` ",
            "is honoured only up to that cap. Pass `signal` to interrupt a retry wait.\n\n"
        ),
    });
    text.push_str("## Quick start\n\n");
    match (identity, quick_start(model)) {
        (None, _) => {
            let _ = writeln!(text, "{NO_IDENTITY_NOTE}");
        }
        (Some(_), None) => text.push_str(
            "No operation has a sample call; `reference.md` says why under each operation.\n",
        ),
        (Some(_), Some((operation, request_line, block))) => {
            let _ = write!(
                text,
                "Calling {} ({}), as `reference.md` prints it:\n\n{block}",
                code_span(operation),
                code_span(request_line)
            );
        }
    }
    text
}

/// The stable code for "a package loader stage failed", which the reference never publishes.
///
/// Matching the CODE is what this identity is for — it is the same key `DiagnosticPolicy` matches
/// on — so this is a policy decision about a class of diagnostic, not a reading of its text.
const SOURCE_LOAD_FAILED: &str = "source.load.failed";

/// Whether a diagnostic belongs in a published SDK reference.
///
/// Two clauses, for two different reasons. Both exist because a generated document is COMMITTED:
/// it is read by people who did not run the pipeline, and it is compared byte-for-byte by
/// `gnr8 check`.
///
/// 1. **The location must name a file inside the analyzed module.** A location outside it — a
///    dependency, the standard library, a downloaded toolchain under the module cache — is not a
///    fact about the API this document describes, and it is machine-dependent: it holds the
///    reader's home directory and module-cache layout. Publishing one makes two developers with
///    byte-identical source commit different bytes, which surfaces as `gnr8 check` drift that no
///    source change explains (issue #67).
///
/// 2. **It must describe the API, not whether the source could be read at all.** A load failure
///    means there was no surface to describe, so it is not a gap in the published contract — and
///    its message is the package loader's own text, which can quote a filesystem path wherever the
///    loader chose to. Excluding the class removes that whole exposure without gnr8 ever reading a
///    diagnostic's message to decide.
///
/// Nothing is lost. Every diagnostic still travels with the graph and still reaches
/// `gnr8 inspect graph`, `gnr8 doctor` (which exits non-zero on error severity), and `-v` output —
/// reports, rather than committed artifacts.
pub(crate) fn is_publishable(diagnostic: &crate::graph::Diagnostic) -> bool {
    crate::graph::is_module_relative(&diagnostic.file) && diagnostic.code != SOURCE_LOAD_FAILED
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::{write_sdk_docs, SdkDocs};
    use crate::graph::{
        ApiGraph, Diagnostic, DiagnosticCategory, Operation, OperationDocsPolicy, SourceSpan,
    };
    use crate::sdk::builtins::SiblingSdk;
    use crate::sdk::prelude::{GoSdk, PySdk, SdkPackageMetadata, TsSdk};
    use crate::sdk::Artifacts;

    /// The `reference.md` a Go SDK writes for `graph`.
    fn sdk_reference(_language: &str, _package: &str, graph: &ApiGraph) -> String {
        let mut graph = graph.clone();
        if graph.title.is_empty() {
            graph.title = "Probe".to_string();
        }
        let go = GoSdk::new().module("example.com/sdk").to("sdk");
        let mut out = Artifacts::new();
        write_sdk_docs(&mut out, SiblingSdk::Go(&go), &graph, &go.docs).unwrap();
        out.into_files()
            .into_iter()
            .find(|artifact| artifact.path == "sdk/reference.md")
            .map(|artifact| artifact.text)
            .unwrap()
    }

    #[test]
    fn bool_conversion_maps_true_to_reference_and_false_to_none() {
        assert!(!SdkDocs::from(true).is_none());
        assert!(SdkDocs::from(false).is_none());
    }

    fn diagnostic(code: &str, severity: &str, message: &str, file: &str) -> Diagnostic {
        Diagnostic::new(
            code,
            DiagnosticCategory::Source,
            severity,
            message,
            SourceSpan {
                file: file.to_string(),
                start_line: 1,
                end_line: 1,
            },
        )
    }

    /// A diagnostic about the API surface, which is what the section is for.
    fn contract_diagnostic(severity: &str, message: &str, file: &str) -> Diagnostic {
        diagnostic("request.parameter.unresolved", severity, message, file)
    }

    /// A diagnostic about a package that did not load, which is not.
    fn load_failure(message: &str, file: &str) -> Diagnostic {
        diagnostic("source.load.failed", "ERROR", message, file)
    }

    fn graph_with(diagnostics: Vec<Diagnostic>) -> ApiGraph {
        ApiGraph {
            diagnostics,
            ..ApiGraph::default()
        }
    }

    fn operation(id: &str, group: Option<&str>) -> Operation {
        Operation {
            id: id.to_string(),
            method: "GET".to_string(),
            path: format!("/{id}"),
            handler: id.to_string(),
            summary: Some(format!("Document {id}.")),
            description: None,
            group: group.map(str::to_string),
            middleware: Vec::new(),
            params: Vec::new(),
            request_body: None,
            request_body_required: true,
            request_body_content_type: None,
            request_body_variants: Vec::new(),
            responses: Vec::new(),
            security: Vec::new(),
            security_overrides_global: false,
            provenance: SourceSpan {
                file: "books.rs".to_string(),
                start_line: 1,
                end_line: 1,
            },
        }
    }

    #[test]
    fn reference_uses_canonical_tags_for_policy_group_and_empty_results() {
        let mut grouped = operation("grouped", Some("Books"));
        grouped.summary = None;
        let graph = ApiGraph {
            operations: vec![
                grouped,
                operation("classified", Some("Reports")),
                operation("untagged", None),
            ],
            operation_docs: vec![OperationDocsPolicy {
                operation_id: "classified".to_string(),
                openapi_operation_id: None,
                deprecated: false,
                tags: vec!["internal".to_string(), "partner".to_string()],
                request_examples: Vec::new(),
                request_content_types: Vec::new(),
                responses: Vec::new(),
            }],
            ..ApiGraph::default()
        };

        let reference = sdk_reference("Go", "example.com/sdk", &graph);
        assert!(reference.contains("Tags: `Books`"), "{reference}");
        assert!(
            reference.contains("Tags: `internal`, `partner`"),
            "{reference}"
        );
        assert!(!reference.contains("Tags: `Reports`"), "{reference}");
        assert!(reference.contains("\n## `untagged`\n"), "{reference}");
        let untagged = reference
            .split("\n## `untagged`\n")
            .nth(1)
            .unwrap_or_default();
        let untagged = untagged.split("\n## ").next().unwrap_or_default();
        assert!(!untagged.contains("Tags:"), "{untagged}");
    }

    /// A diagnostic about the analyzed module is exactly what this section is for: it tells an
    /// agent reading the SDK what the API contract does not state.
    #[test]
    fn a_diagnostic_inside_the_module_is_published() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "untyped query param 'genre' on GET /books",
                "internal/http/handlers.go",
            )]),
        );
        assert!(reference.contains("## Diagnostics"), "{reference}");
        assert!(
            reference.contains(
                "- WARN: untyped query param 'genre' on GET /books (internal/http/handlers.go:1)"
            ),
            "{reference}"
        );
    }

    /// Clause 1, isolated: a location outside the module carries the reader's home directory, so
    /// two developers with byte-identical source would commit different documents and `gnr8 check`
    /// would report drift that no source change explains (issue #67). The diagnostic is an ordinary
    /// contract diagnostic, so ONLY its location can be what excludes it.
    #[test]
    fn a_diagnostic_outside_the_module_is_not_published() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "untyped query param 'genre' on GET /books",
                "/Users/someone/go/pkg/mod/example.com/dep@v1.2.3/handlers.go",
            )]),
        );
        assert!(
            !reference.contains("## Diagnostics"),
            "a section with nothing publishable must not be emitted: {reference}"
        );
        assert!(!reference.contains("/Users/someone"), "{reference}");
    }

    /// Clause 2, isolated: a package that did not load leaves no API surface to describe, and its
    /// message is the package loader's own text, which can quote a filesystem path wherever the
    /// loader chose to. The location here is inside the module, so ONLY the class can exclude it.
    #[test]
    fn a_load_failure_is_not_published_even_from_inside_the_module() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![load_failure(
                "go/packages list error: no required module provides package x; \
                 open /Users/someone/go/pkg/mod/x: no such file",
                "internal/http/handlers.go",
            )]),
        );
        assert!(
            !reference.contains("## Diagnostics"),
            "a section with nothing publishable must not be emitted: {reference}"
        );
        assert!(!reference.contains("/Users/someone"), "{reference}");
        assert!(!reference.contains("go/packages list error"), "{reference}");
    }

    /// One unpublishable diagnostic must not take the publishable ones with it.
    #[test]
    fn publishable_diagnostics_survive_alongside_an_unpublishable_one() {
        let reference = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![
                load_failure(
                    "go/packages type error: boom",
                    "/home/runner/go/pkg/mod/dep/dep.go",
                ),
                contract_diagnostic("WARN", "dynamic response in handler listBooks", "main.go"),
            ]),
        );
        assert!(reference.contains("## Diagnostics"), "{reference}");
        assert!(
            reference.contains("- WARN: dynamic response in handler listBooks (main.go:1)"),
            "{reference}"
        );
        assert!(!reference.contains("/home/runner"), "{reference}");
    }

    /// The rendered document must not depend on the machine that rendered it. Rendering the same
    /// graph on a host with a POSIX module cache and on one with a Windows module cache has to
    /// produce the same bytes, or the determinism guarantee holds only within one operating system.
    #[test]
    fn rendering_is_identical_whichever_absolute_path_shape_the_host_uses() {
        let posix = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "boom",
                "/home/runner/go/pkg/mod/dep/dep.go",
            )]),
        );
        let windows = sdk_reference(
            "Go",
            "example.com/sdk",
            &graph_with(vec![contract_diagnostic(
                "WARN",
                "boom",
                r"C:\Users\runner\go\pkg\mod\dep\dep.go",
            )]),
        );
        assert_eq!(posix, windows);
    }

    /// A small API with an error body, security and a diagnostic naming no operation.
    fn shop() -> ApiGraph {
        serde_json::from_value(serde_json::json!({
            "module": "example.com/shop",
            "title": "Shop API",
            "base_path": "/",
            "security": [
                {"id": "ApiKeyAuth", "kind": "apiKey", "location": "header", "name": "X-API-Key"}
            ],
            "diagnostics": [{
                "code": "source.openapi.unrepresentable", "severity": "WARN",
                "category": "source", "message": "server path dropped",
                "file": "api\\spec.yaml", "line": 3,
                "span": {"file": "api\\spec.yaml", "start_line": 3, "end_line": 3}
            }],
            "operations": [{
                "id": "getItem", "method": "GET", "path": "/items/{id}", "handler": "getItem",
                "summary": "Returns one item.",
                "params": [{"name": "id", "location": "path", "required": true,
                            "schema": {"type": "primitive", "of": {"prim": "string"}},
                            "provenance": {"file": "a.go", "start_line": 1, "end_line": 1}}],
                "request_body": null,
                "responses": [
                    {"status": 200, "body": {"ref_id": "shop.Item"}, "content_types": ["application/json"]},
                    {"status": 404, "body": {"ref_id": "shop.Problem"}, "content_types": ["application/json"]}
                ],
                "provenance": {"file": "a.go", "start_line": 1, "end_line": 1}
            }],
            "schemas": [
                {"id": "shop.Item", "name": "Item", "body": {"type": "object", "of": [
                    {"json_name": "name", "serializer_may_omit": false,
                     "deserializer_accepts_absent": false, "deserializer_accepts_null": false,
                     "serializer_may_emit_null": false, "validator_requires_presence": true,
                     "validator_rejects_null": true,
                     "schema": {"type": "primitive", "of": {"prim": "string"}}}
                ]}, "provenance": {"file": "a.go", "start_line": 1, "end_line": 1}},
                {"id": "shop.Problem", "name": "Problem", "body": {"type": "object", "of": [
                    {"json_name": "code", "serializer_may_omit": false,
                     "deserializer_accepts_absent": false, "deserializer_accepts_null": false,
                     "serializer_may_emit_null": false, "validator_requires_presence": true,
                     "validator_rejects_null": true,
                     "schema": {"type": "primitive", "of": {"prim": "string"}}}
                ]}, "provenance": {"file": "a.go", "start_line": 1, "end_line": 1}}
            ]
        }))
        .unwrap()
    }

    /// Every file an SDK's docs write, by path.
    fn sdk_docs(
        sdk: SiblingSdk<'_>,
        graph: &ApiGraph,
    ) -> std::collections::BTreeMap<String, String> {
        let mut out = Artifacts::new();
        let docs = SdkDocs::from(true);
        write_sdk_docs(&mut out, sdk, graph, &docs).unwrap();
        out.into_files()
            .into_iter()
            .map(|artifact| (artifact.path, artifact.text))
            .collect()
    }

    /// The README names the one consumer identity — what to import and the language's own install
    /// command — and its quick start is the first sampled call, byte for byte as `reference.md`
    /// prints it under that operation.
    #[test]
    fn readme_names_the_identity_and_quotes_the_reference_call() {
        let py = PySdk::new()
            .module("example.com/shop/shop")
            .package(SdkPackageMetadata::new().registry_name("shop-sdk"))
            .to("py");
        let files = sdk_docs(SiblingSdk::Python(&py), &shop());
        let readme = &files["py/README.md"];
        assert!(
            readme.contains("- Import: `shop`\n- Install: `pip install shop-sdk`\n"),
            "{readme}"
        );
        assert!(
            readme.contains("4. Handle generated `ApiError` values"),
            "{readme}"
        );
        let block = readme
            .split("## Quick start\n\n")
            .nth(1)
            .and_then(|rest| rest.split_once("\n\n"))
            .map(|(intro, block)| {
                assert_eq!(
                    intro,
                    "Calling `getItem` (`GET /items/{id}`), as `reference.md` prints it:"
                );
                block
            })
            .unwrap();
        assert!(
            block.starts_with("```python\nfrom shop import Client\n"),
            "{block}"
        );
        assert!(files["py/reference.md"].contains(block), "{block}");
    }

    /// An SDK with no package metadata has no import to name, so its README says so in place of
    /// the import, the install line and the quick start.
    #[test]
    fn readme_without_an_identity_says_why_it_has_no_quick_start() {
        let ts = TsSdk::new().module("shop").to("ts");
        let files = sdk_docs(SiblingSdk::TypeScript(&ts), &shop());
        let readme = &files["ts/README.md"];
        assert!(!readme.contains("- Import:"), "{readme}");
        assert!(!readme.contains("- Install:"), "{readme}");
        assert!(
            readme.ends_with(&format!("## Quick start\n\n{}\n", super::NO_IDENTITY_NOTE)),
            "{readme}"
        );
    }

    /// `reference.md` is one file: the docs pages as sections one heading level down under its own
    /// title, its one link `README.md`, every other reference a code span, and errors, credentials
    /// and samples scoped to this SDK alone. A diagnostic naming no operation is printed once, its
    /// path with `/`.
    #[test]
    fn reference_is_one_file_scoped_to_its_sdk() {
        let go = GoSdk::new().module("example.com/shop/sdk").to("go");
        let files = sdk_docs(SiblingSdk::Go(&go), &shop());
        let reference = &files["go/reference.md"];
        assert!(
            reference.starts_with(
                "# Shop API Go SDK reference\n\nGenerated by `gnr8` for `example.com/shop/sdk`. \
                 [README.md](README.md) shows how to install it and construct the client.\n\n## Shop API\n"
            ),
            "{reference}"
        );
        assert_eq!(reference.matches("\n# ").count(), 0, "{reference}");
        assert_eq!(reference.matches("](").count(), 1, "{reference}");
        for section in [
            "\n## `getItem`\n",
            "\n### Example\n",
            "\n#### Go — `example.com/shop/sdk`\n",
            "\n## `Problem`\n",
            "\n## Errors\n",
            "\n## Authentication\n",
            "\n### `ApiKeyAuth`\n",
        ] {
            assert!(reference.contains(section), "{section} in:\n{reference}");
        }
        assert!(
            reference.contains("including a status the API does not declare: Go `*APIError`.\n"),
            "{reference}"
        );
        assert!(!reference.contains("Python"), "{reference}");
        assert!(!reference.contains("TypeScript"), "{reference}");
        assert!(
            reference.contains("Handling the `404` reply:"),
            "{reference}"
        );
        assert_eq!(
            reference
                .matches("- WARN: server path dropped (api/spec.yaml:3)\n")
                .count(),
            1,
            "{reference}"
        );
    }
}
